name: Monitor

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          azPSVersion: latest
          inlineScript: |
            $result = docker run --rm ghcr.io/mthalman/dredge image compare layers --output json alpine:latest ghcr.io/mthalman/bump-test:main --os linux --arch amd64 | ConvertFrom-Json
            if ($result.Summary.TargetIncludesAllBaseLayers) {
              Write-Host "Equal"
            }
            else {
              Write-Host "Not Equal"
            }
